### ISSUE TITLE
Arduino ethernet not getting IP

### ISSUE THREAD

**Issue by jmerriweather** [xorbit/wesp32-demos#2]
I can't seem to get any of the Arduino examples working, ethernet never gets an IP address. The original Micropython worked and successfully got an IP address.

Any ideas?

**Comment by xorbit** [comment]
Did you select "Silicognition wESP32" under Tools -> Board?  This needs to be done to configure the RMII pins to the PHY correctly.

**Comment by jmerriweather** [comment]
yes i selected Silicognition wESP32

**Comment by xorbit** [comment]
Not sure what to tell you.  Maybe try one of the MicroPython examples to confirm the hardware is still OK?
